# Generated by Django 4.1.13 on 2025-12-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('is_fainting', models.BooleanField(default=False, help_text='Does this goat faint when scared?')),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
