# Generated by Django 4.1.13 on 2025-12-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_goat_id_goatlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrazingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#FF0000', max_length=20)),
                ('coordinates', models.TextField(help_text='JSON list of {lat, lng} points')),
            ],
        ),
    ]
