# Generated by Django 4.1.13 on 2025-12-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_dailytask_taskcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='time_of_day',
            field=models.CharField(choices=[('AM', 'Morning'), ('PM', 'Evening'), ('ANY', 'Anytime')], default='ANY', max_length=3),
        ),
    ]
