# Generated by Django 4.1.13 on 2025-12-15 22:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_dailytask_time_of_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(help_text='e.g. 555-123-4567', max_length=20)),
                ('address', models.TextField(help_text='Full address for map navigation')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('record_type', models.CharField(choices=[('Vaccine', 'Vaccination'), ('Deworm', 'Deworming'), ('Hoof', 'Hoof Trim'), ('Checkup', 'General Checkup'), ('Illness', 'Illness/Injury')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('next_due_date', models.DateField(blank=True, help_text='When is this due next?', null=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='farm.goat')),
            ],
        ),
    ]
