# Generated by Django 4.1.13 on 2025-12-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_vet_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='status',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('Vet', 'At Vet'), ('Deceased', 'Deceased')], default='Healthy', max_length=20),
        ),
    ]
