# Generated by Django 4.1.13 on 2025-12-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_goat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='birthdate',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='goat',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Approx Age (if birthdate unknown)'),
        ),
    ]
