# Generated by Django 4.1.13 on 2025-12-15 22:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_goat_birthdate_alter_goat_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Homestead', max_length=200)),
                ('owner', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('feed_type', models.CharField(choices=[('Hay', 'Hay'), ('Grain', 'Grain'), ('Minerals', 'Minerals'), ('Treats', 'Treats'), ('Other', 'Other')], max_length=20)),
                ('amount', models.CharField(help_text='e.g. 1 Scoop, 2 Flakes', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_logs', to='farm.goat')),
            ],
        ),
        migrations.CreateModel(
            name='BreedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mate_name', models.CharField(max_length=100, verbose_name='Buck/Partner Name')),
                ('breeding_date', models.DateField()),
                ('due_date', models.DateField(blank=True, help_text='Auto-calculated (150 days) if left blank', null=True)),
                ('notes', models.TextField(blank=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_logs', to='farm.goat')),
            ],
        ),
    ]
