# Generated by Django 4.1.13 on 2025-12-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_farmsettings_alter_medicalrecord_next_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Alfalfa Hay, Goat Pellets', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('unit', models.CharField(default='lbs', help_text='e.g. Bales, Bags, lbs', max_length=20)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=5.0, help_text='Alert when stock drops below this', max_digits=7)),
            ],
        ),
    ]
