# Generated by Django 4.1.13 on 2025-12-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_feeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsettings',
            name='google_maps_api_key',
            field=models.CharField(blank=True, default='', help_text='Your Google Maps API Key', max_length=100),
        ),
        migrations.AddField(
            model_name='farmsettings',
            name='latitude',
            field=models.FloatField(default=40.85907),
        ),
        migrations.AddField(
            model_name='farmsettings',
            name='longitude',
            field=models.FloatField(default=-79.78674),
        ),
    ]
