# Generated by Django 4.1.13 on 2025-12-15 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_farmsettings_google_maps_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Evening')], default='AM', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in lbs', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_logs', to='farm.goat')),
            ],
        ),
    ]
