# Generated by Django 4.1.13 on 2025-12-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_milklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goats/'),
        ),
        migrations.AlterField(
            model_name='farmsettings',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='farmsettings',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
