# Generated by Django 4.1.13 on 2025-12-16 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_goat_image_alter_farmsettings_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Expense', 'Expense 💸'), ('Income', 'Income 💰')], default='Expense', max_length=10)),
                ('category', models.CharField(choices=[('Feed', 'Feed & Hay'), ('Vet', 'Vet & Medical'), ('Equipment', 'Equipment & Supplies'), ('Goat Sale', 'Goat Sale'), ('Product Sale', 'Product Sale (Milk/Soap)'), ('Other', 'Other')], default='Other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
