# Generated by Django 4.1.13 on 2025-12-16 23:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in lbs', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='farm.goat')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
