# Generated by Django 4.1.13 on 2025-12-16 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_weightlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(default='General', help_text='e.g. Maintenance, Show, Purchase', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
