# Generated by Django 4.1.13 on 2025-12-17 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_farmevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmevent',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='farmevent',
            name='category',
            field=models.CharField(default='General', help_text='e.g. Vet, Show, Maintenance', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
