# Generated by Django 4.1.13 on 2025-12-17 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0017_farmevent_end_date_alter_farmevent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='dam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kids_dam', to='farm.goat', verbose_name='Dam (Mother)'),
        ),
        migrations.AddField(
            model_name='goat',
            name='sire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kids_sire', to='farm.goat', verbose_name='Sire (Father)'),
        ),
    ]
