# Generated by Django 4.2.27 on 2025-12-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0018_goat_dam_goat_sire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch', models.CharField(blank=True, help_text='Batch/Lot Number', max_length=50)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Current stock level', max_digits=10)),
                ('unit', models.CharField(choices=[('ml', 'ml/cc'), ('g', 'grams'), ('pill', 'pills/bolus'), ('oz', 'ounces')], default='ml', max_length=10)),
                ('dosage_amount', models.DecimalField(decimal_places=2, default=1.0, help_text='Dose Amount', max_digits=5)),
                ('dosage_weight_interval', models.DecimalField(decimal_places=2, default=0.0, help_text='Per X lbs bodyweight. Set to 0 for fixed dose.', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Withdrawal times, warnings, etc.')),
            ],
        ),
    ]
