# Generated by Django 4.2.27 on 2025-12-17 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoatPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goat_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='farm.goat')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
