# Generated by Django 4.2.27 on 2025-12-17 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0020_goatphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='goatphoto',
            options={'verbose_name': 'Goat Photo', 'verbose_name_plural': 'Goat Photos'},
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_gender', models.CharField(choices=[('Any', 'Any'), ('Doe', 'Doe'), ('Buck', 'Buck'), ('Wether', 'Wether')], default='Any', max_length=10)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Fulfilled', 'Fulfilled'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='farm.customer')),
                ('preferred_dam', models.ForeignKey(blank=True, help_text='Optional specific doe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_requests', to='farm.goat')),
            ],
        ),
    ]
