# Generated by Django 4.2.27 on 2025-12-17 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0021_customer_alter_goatphoto_options_waitinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(help_text='Date the sale was finalized')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid_in_full', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='farm.customer')),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='farm.goat')),
            ],
        ),
    ]
