# Generated by Django 4.2.27 on 2025-12-20 15:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(default=django.utils.timezone.now)),
                ('live_weight', models.DecimalField(decimal_places=2, help_text='Weight before processing (lbs)', max_digits=5)),
                ('hanging_weight', models.DecimalField(decimal_places=2, help_text='Carcass weight (lbs)', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Cut details, quality notes, etc.')),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='farm.goat')),
            ],
        ),
    ]
