# Generated by Django 4.2.28 on 2026-02-14 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0023_meatharvest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedinglog',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Auto-calculated if left blank', null=True),
        ),
        migrations.AlterField(
            model_name='farmevent',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='next_due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiration_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='milklog',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], default='Expense', max_length=10),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
