# Generated by Django 6.0.2 on 2026-02-24 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0023_meatharvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='gender',
            field=models.CharField(blank=True, choices=[('Doe', 'Doe (Female)'), ('Buck', 'Buck (Male)'), ('Wether', 'Wether (Castrated Male)'), ('Doeling', 'Doeling (Young Female)'), ('Buckling', 'Buckling (Young Male)')], default='Doe', max_length=10),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
