# Generated by Django 6.0.2 on 2026-02-24 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0024_goat_gender_alter_taskcompletion_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('marker_type', models.CharField(choices=[('Barn', 'Barn'), ('Shelter', 'Shelter'), ('Water', 'Water Trough'), ('Feeder', 'Feeder'), ('Gate', 'Gate'), ('Other', 'Other')], default='Other', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('Vaccine', 'Vaccination'), ('Deworm', 'Deworming'), ('Hoof', 'Hoof Trim'), ('Checkup', 'General Checkup')], max_length=20)),
                ('interval_days', models.IntegerField(help_text='Days between treatments')),
                ('last_performed', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('goat', models.ForeignKey(blank=True, help_text='Leave blank for herd-wide schedule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_schedules', to='farm.goat')),
            ],
        ),
        migrations.CreateModel(
            name='PastureAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently active', null=True)),
                ('notes', models.TextField(blank=True)),
                ('goats', models.ManyToManyField(blank=True, related_name='pasture_assignments', to='farm.goat')),
                ('grazing_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='farm.grazingarea')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PastureCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('score', models.IntegerField(help_text='Forage quality 1-5')),
                ('notes', models.TextField(blank=True)),
                ('grazing_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='farm.grazingarea')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
