# Generated by Django 4.2.28 on 2026-02-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0024_alter_breedinglog_due_date_alter_farmevent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='barcode',
            field=models.CharField(blank=True, default='', help_text='UPC/EAN barcode', max_length=50),
        ),
        migrations.AddField(
            model_name='goat',
            name='microchip_id',
            field=models.CharField(blank=True, default='', help_text='Microchip/EID number', max_length=30),
        ),
        migrations.AddField(
            model_name='goat',
            name='scrapie_tag',
            field=models.CharField(blank=True, help_text='Official USDA Scrapie Tag ID', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, default='', help_text='UPC/EAN barcode', max_length=50),
        ),
        migrations.AddField(
            model_name='milklog',
            name='butterfat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Butterfat %', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='milklog',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Protein %', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='milklog',
            name='somatic_cell_count',
            field=models.PositiveIntegerField(blank=True, help_text='SCC (x1000 cells/ml)', null=True),
        ),
    ]
