# Generated by Django 6.0.2 on 2026-02-24 12:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0025_mapmarker_medicalschedule_pastureassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pen_type', models.CharField(choices=[('Kidding', 'Kidding Pen'), ('Buck', 'Buck Pen'), ('Doe', 'Doe Pen'), ('Kid', 'Kid Pen'), ('Sick', 'Sick Pen'), ('General', 'General')], default='General', max_length=10)),
                ('capacity', models.IntegerField(default=5)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Feed', 'Feed & Hay'), ('Equipment', 'Equipment'), ('Vet', 'Veterinary'), ('Shearing', 'Shearing'), ('Fencing', 'Fencing'), ('Other', 'Other')], default='Other', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='goat',
            field=models.ForeignKey(blank=True, help_text='Optional: link expense to a specific goat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='farm.goat'),
        ),
        migrations.CreateModel(
            name='GoatDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='goat_documents/')),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('Registration', 'Registration Papers'), ('Vet Report', 'Vet Report'), ('Receipt', 'Purchase Receipt'), ('Insurance', 'Insurance'), ('Certificate', 'Certificate'), ('Other', 'Other')], default='Other', max_length=20)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='farm.goat')),
            ],
            options={
                'ordering': ['-date_uploaded'],
            },
        ),
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('famacha_score', models.IntegerField(blank=True, help_text='1=Red(healthy) to 5=White(anemic)', null=True)),
                ('body_condition_score', models.DecimalField(blank=True, decimal_places=1, help_text='1=Emaciated to 5=Obese (0.5 steps)', max_digits=2, null=True)),
                ('notes', models.TextField(blank=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='farm.goat')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HeatObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observed', models.DateField(default=django.utils.timezone.now)),
                ('signs', models.CharField(blank=True, help_text='e.g. flagging, mounting, mucus discharge', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_observations', to='farm.goat')),
            ],
            options={
                'ordering': ['-date_observed'],
            },
        ),
        migrations.CreateModel(
            name='KiddingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kidding_date', models.DateField(default=django.utils.timezone.now)),
                ('num_kids_born', models.IntegerField(default=1)),
                ('num_alive', models.IntegerField(default=1)),
                ('num_stillborn', models.IntegerField(default=0)),
                ('birth_type', models.CharField(choices=[('Single', 'Single'), ('Twins', 'Twins'), ('Triplets', 'Triplets'), ('Quads', 'Quads')], default='Single', max_length=10)),
                ('presentation', models.CharField(choices=[('Normal', 'Normal'), ('Breach', 'Breach'), ('Other', 'Other')], default='Normal', max_length=10)),
                ('assisted', models.BooleanField(default=False)),
                ('complications', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('breeding_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kidding_records', to='farm.breedinglog')),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kidding_records', to='farm.goat')),
            ],
            options={
                'ordering': ['-kidding_date'],
            },
        ),
        migrations.CreateModel(
            name='PenAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(default=django.utils.timezone.now)),
                ('date_out', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pen_assignments', to='farm.goat')),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='farm.pen')),
            ],
            options={
                'ordering': ['-date_in'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='farm.supplier'),
        ),
    ]
