# Generated by Django 4.2.28 on 2026-02-14 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0025_add_scrapie_quality_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedinglog',
            name='feed_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_logs', to='farm.feeditem'),
        ),
        migrations.AddField(
            model_name='feedinglog',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric feed amount', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='feedinglog',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Unit for numeric amount', max_length=20),
        ),
        migrations.AddField(
            model_name='goat',
            name='grazing_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goats', to='farm.grazingarea'),
        ),
    ]
