# Generated by Django 6.0.2 on 2026-02-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0026_pen_supplier_transaction_goat_goatdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='external_owner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='goat',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goat',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='goat',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
