# Generated by Django 6.0.2 on 2026-03-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0027_goat_external_owner_goat_is_external_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('Vaccine', 'Vaccination'), ('Deworm', 'Deworming'), ('Hoof', 'Hoof Trim'), ('Checkup', 'General Checkup'), ('Illness', 'Illness/Injury'), ('Procedure', 'Procedure'), ('Vitamins', 'Vitamins')], max_length=20),
        ),
    ]
