# Generated by Django 6.0.2 on 2026-03-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0028_alter_medicalrecord_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='microchip',
            field=models.CharField(blank=True, help_text='Microchip ID number', max_length=100),
        ),
    ]
