# Generated by Django 6.0.2 on 2026-03-10 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0029_goat_microchip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedinglog',
            name='feed_type',
            field=models.CharField(choices=[('Hay', 'Hay'), ('Grain', 'Grain'), ('Minerals', 'Minerals'), ('Water', 'Water'), ('Crackers/Cookies', 'Crackers/Cookies'), ('Veggies', 'Veggies'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedinglog',
            name='goat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_logs', to='farm.goat'),
        ),
    ]
