# Generated by Django 6.0.2 on 2026-03-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0030_alter_feedinglog_feed_type_alter_feedinglog_goat'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsettings',
            name='timezone',
            field=models.CharField(choices=[('America/New_York', 'Eastern (ET)'), ('America/Chicago', 'Central (CT)'), ('America/Denver', 'Mountain (MT)'), ('America/Los_Angeles', 'Pacific (PT)'), ('America/Anchorage', 'Alaska (AKT)'), ('Pacific/Honolulu', 'Hawaii (HT)'), ('UTC', 'UTC')], default='America/New_York', max_length=50),
        ),
    ]
