# Generated by Django 6.0.2 on 2026-03-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0030_alter_feedinglog_feed_type_alter_feedinglog_goat'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsettings',
            name='timezone',
            field=models.CharField(choices=[('US/Eastern', 'Eastern (ET)'), ('US/Central', 'Central (CT)'), ('US/Mountain', 'Mountain (MT)'), ('US/Pacific', 'Pacific (PT)'), ('US/Alaska', 'Alaska (AKT)'), ('US/Hawaii', 'Hawaii (HT)'), ('UTC', 'UTC')], default='US/Eastern', max_length=50),
        ),
    ]
