# Generated by Django 6.0.2 on 2026-03-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0031_farmsettings_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedinglog',
            name='feeding_time',
            field=models.TimeField(blank=True, help_text='Actual time of feeding', null=True),
        ),
        migrations.AddField(
            model_name='feedinglog',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=10),
        ),
    ]
